# 지킬에 오신 것을 환영합니다!
#
# 이 구성 파일은 전체 블로그, 값에 영향을 미치는 설정을 의미합니다.
# 한번 설정해야 하며 그 후에는 편집하는 일이 거의 없습니다.
# 자신이 이 파일을 매우 자주 편집하는 경우, 지킬 데이터 파일 사용을 고려해 보세요.
# 기능의 사용을 중지하거나 계속할 경우, 자주 편집할 수도 있습니다.
#
# 이 파일을 사용하게 되면 기술적인 이유로 다시 로드 됩니다.
# 'bundle execJekoll services'라는 파일을 변경하는 경우 서버 프로세스를 다시 시작하십시오. (가능하면 편집하지 마세요.)

# 사이트 설정
# 새 사이트를 관리자가 설정하는데 사용됩니다. 만약 당신이 HTML파일을 본다면,
# 이들이{{Site.title2}},{{Site.Mail2}}등을 통해 액세스 되는 것을 참조하세요.
# 원하는 사용자 지정 변수를 생성할 수 있으며 이들 변수에 액세스 할 수 있습니다.
# 템플릿에서 다음을 수행합니다.

lang: en-US # 사이트의 기본 언어를 설정합니다.
title: 미디어센터 # 사이트의 이름을 설정합니다.
email: skhumedia@outlook.com # 사이트의 기본 이메일을 지정합니다.
description: # 다음은 요약입니다. (탭핑 된 영역 참조)
baseurl: /skhumedia.github.io # 사용자 사이트의 선택적 하위 페이지를 설정합니다. (예: /site url)
url: "https://skhumedia.github.io" # 당신의 사이트를 위한 기본 호스트 이름과 프로토콜을 설정합니다. "https://skhumedia.github.io"
author: # 다음은 저자입니다. (탭핑 된 영역 참조)
  name: 미디어센터 홈페이지 관리자 # 사이트 관리자는 MediaCenter Admin으로 표기합니다. (가능하면 편집하지 마세요.)
  picture: # 소개합니다의 사진 출처 링크가 들어갑니다.
  facebook_username: skhu.media.center # 미디어 센터 페이스북 페이지 계정이 들어갑니다.
logo: /assets/images/logo.jpg # 사이트 로고 경로(예: /assets/images/logo.png)
search: true # 검색기능을 끄거나 켭니다. (true or false)
search_full_content: false # 검색의 기능을 강화합니다. (true or false)
search_provider: lunr # 검색을 제공하는 참조영역을 설정합니다. (lunr or algolia)
algolia: # 다음은 검색 기능을 제공하는 algolia 설정 입니다. (탭핑 된 영역 참조)
  application_id: # YOUR_APPLICATION_ID 설정합니다.
  index_name: # YOUR_INDEX_NAME 설정합니다.
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY 설정합니다.
  powered_by: # true or false

# 사이트 빌드 설정 (절대 편집하지 마세요.)
markdown: kramdown
plugins: # 이전 gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# 페이지화 설정 부분 - https://jekyllrb.com/docs/pagination/
paginate: 10 # 페이지 수를 지정합니다.
paginate_path: /page:num/ # 페이지는 콘텐츠 수만큼 할당됩니다.

# 빠른 수행을 위해 제외한 것
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 전면 매터 기본 값
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
